### ISSUE TITLE
Cannot download supernet chechpoint

### ISSUE THREAD

**Issue by liqi17thu** [mit-han-lab/once-for-all#10]
I try to download your supernet weights but it seems no connection?
![image](https://user-images.githubusercontent.com/48043983/80281598-e650d280-873e-11ea-9a14-1317e65f47ee.png)

**Comment by zhangyuan1994511** [comment]
@Han Cai ,I have the same problem~

**Comment by han-cai** [comment]
Sorry about this. It is because our server is currently down. It should be fixed once our server is back online.

**Comment by zhangyuan1994511** [comment]
OK, I get it, Thank you very much!

**Comment by sahnimanas** [comment]
@han-cai thanks for making the models available on Google Drive. Can the teacher model also be added there? The server seems to be down again (https://hanlab.mit.edu/files/OnceForAll/ofa_checkpoints/ofa_D4_E6_K7)

**Comment by zanonShao** [comment]
@han-cai  It looks like the server has been down for a long time, is it possible to share the teacher model in another way？Thanks。

**Comment by han-cai** [comment]
I just updated the URL links in the code. Now, it will automatically download the checkpoints from our backup server.
