### ISSUE TITLE
ImportError: Extension horovod.torch

### ISSUE THREAD

**Issue by abhiagwl4262** [mit-han-lab/once-for-all#19]
@zhijian-liu @Lyken17  @tonylins  @mzahran001 @songhan  ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error

**Comment by Lyken17** [comment]
Which command did you run? Evaluation or training?

**Comment by abhiagwl4262** [comment]
@Lyken17 It was in the train.

**Comment by abhiagwl4262** [comment]
@Lyken17 Now I am trying to set up horovod with docker using the following docker image - 

horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu. And Its giving me -

Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from

**Comment by Lyken17** [comment]
it seems like an error from your environment rather than our code.

**Comment by abhiagwl4262** [comment]
@Lyken17 It looks like the same to me. Can you release the docker file for the enivironment setup or may be release instruction for environment setup ?

**Comment by Lyken17** [comment]
We didn't use docker. We run experiments on servers with CUDA + PyTorch + Horovod installed. You may want to go to docker community for help as it looks like the Nvidia detiver is not enabled in your container.

I'm going to close this issue as it is not related with ofa codebase.
