### ISSUE TITLE
channel sorting for elastic width

### ISSUE THREAD

**Issue by LiuDongyang6** [mit-han-lab/once-for-all#25]
Hi, thx for your work. 
In the paper, for supporting elastic width, a channel sorting algorithm based on the norm of each channel was introduced.  However, i can't find this part in the codes. Could anyone tell me about its location?

**Comment by marvis** [comment]
see re_organize_middle_weights

**Comment by LiuDongyang6** [comment]
> see re_organize_middle_weights

Thank you！
