### ISSUE TITLE
Question about GPU Memory for OFA Progressive Shrinking.

### ISSUE THREAD

**Issue by gunjupark** [mit-han-lab/once-for-all#31]
Hi Han Cai, Thank you so much for responding about previous question very quickly.

I'm trying to train OFA Model(ofa_mbv3) using 4 Nvidia Titan V & 2 Titan RTX GPUs.

But There's a problems when validating subnet models.

I checked below code about progressive shrinking validate.

```
for setting, name in subnet_settings:
    run_manager.write_log('-' * 30 + ' Validate %s ' % name + '-' * 30, 'train', should_print=False)
    run_manager.run_config.data_provider.assign_active_img_size(setting.pop('image_size'))
    dynamic_net.set_active_subnet(**setting)
    run_manager.write_log(dynamic_net.module_str, 'train', should_print=False)

    run_manager.reset_running_statistics(dynamic_net)
    loss, top1, top5 = run_manager.validate(epoch=epoch, is_test=is_test, run_str=name, net=dynamic_net)
    losses_of_subnets.append(loss)
    top1_of_subnets.append(top1)
    top5_of_subnets.append(top5)
    valid_log += '%s (%.3f), ' % (name, top1)
```

Validating 1st loop (about 1st subnet) is no problem.
But when I try to validate 2nd subnet, Error("CUDA out of memory") happened.

My GPUs have 12GB(Titan V) , 24GB(Titan RTX) Memories each.

How big is your GPU memory?
Also, please let me know if there is any guessing or recommendation to solve this error.

Thank you so much.

**Comment by gunjupark** [comment]
I also guessed what makes this error is pytorch's problem.
I'm using Pytorch==1.6.0, horovod==0.20.0 , openmpi==4.0.5

**Comment by gunjupark** [comment]
Fortunately, I found code that makes error in my training env.

```
    def reset_running_statistics(self, net=None):
        from ofa.elastic_nn.utils import set_running_statistics
        if net is None:
            net = self.net
        num_gpu = hvd.size()
        n_images = 2000
        batch_size = (math.ceil(n_images / num_gpu) // 8 + 1) * 8
        n_images = batch_size * num_gpu
        sub_train_loader = self.run_config.random_sub_train_loader(n_images, batch_size,
                                                                   num_replicas=num_gpu, rank=hvd.rank())
        set_running_statistics(net, sub_train_loader, distributed=True)
```

In my my training env, num_gpu = 6 & batch_size =300 ~ 400
Batch_size is too big to run validate when I use few gpus.

so I modified it to hard coding. I can solved it.

**Comment by Hukongtao** [comment]
Can I ask you a question？When I train with two cards on my machine with `horovodrun -np 2 -H localhost:2 python train_ofa_net.py `, The code works fine. But I found that the memory of both processes is on the same card. Do you know why?

**Comment by Hukongtao** [comment]
![image](https://user-images.githubusercontent.com/16505966/149875712-566abd5b-8bb3-4c92-bebc-f8913aec6b19.png)
