### ISSUE TITLE
About model converter code (Pytorch to Tensorflow-Lite) for on-device inference latency test.

### ISSUE THREAD

**Issue by gunjupark** [mit-han-lab/once-for-all#35]
Hi 

I want to use OFA - specialized model on my device.
so I need to convert speicialized ofa model(pytorch) to TF-Lite Model.

I tried to convert model with onnx, but some error occured...
(e.g. ValueError: Shape must be rank 2 but is rank 1 for MatMul ...)

And I want to get Latency Tables using my devices resources also.

How could I get them??
Thank you...

**Comment by gunjupark** [comment]
I just want to get some help for converting model.
or getting operation latencies on devices.

so I'm not need nice clean codes, but some information about it.

**Comment by gunjupark** [comment]
I solved it. 
Keras model implementation -> using TF Lite Converter (v2.4) -> tf lite benchmark's profile time

**Comment by un-knight** [comment]
> I solved it.
> Keras model implementation -> using TF Lite Converter (v2.4) -> tf lite benchmark's profile time

Hi~ I meet the same problem. Would you share the method for converting the PyTorch checkpoint into the tflite model? really thanks.
