### ISSUE TITLE
How to train the supernet?

### ISSUE THREAD

**Issue by Hukongtao** [mit-han-lab/once-for-all#64]
As written in the [documentation](https://github.com/mit-han-lab/once-for-all/blob/master/README.md#how-to-train-ofa-networks)，you can use the following command to train a OFA network:   
```
horovodrun -np 32 -H <server1_ip>:8,<server2_ip>:8,<server3_ip>:8,<server4_ip>:8 \
    python train_ofa_net.py
```
  
But after reading the code, I feel that training a OFA network should take three steps：

```
python train_ofa_net.py --task kernel
python train_ofa_net.py --task depth
python train_ofa_net.py --task expand
```

I don't know if I understand it right

**Comment by callmewenhao** [comment]
i think so! 🤔
