### ISSUE TITLE
torch.hub example is broken

### ISSUE THREAD

**Issue by NicolasHug** [mit-han-lab/once-for-all#73]
Hi all,

We're the maintainers of `torch.hub` and it looks like executing the [once-for-all example](https://pytorch.org/hub/pytorch_vision_once_for_all/) fails with the following error:

```
E           Traceback (most recent call last):
E             File "python_code/pytorch_vision_once_for_all.py", line 15, in <module>
E               manual_subnet = super_net.get_active_subnet(preserve_weight=True)
E             File "/home/circleci/.cache/torch/hub/mit-han-lab_once-for-all_master/ofa/imagenet_classification/elastic_nn/networks/ofa_resnets.py", line 293, in get_active_subnet
E               self.blocks[idx].get_active_subnet(input_channel, preserve_weight)
E             File "/home/circleci/.cache/torch/hub/mit-han-lab_once-for-all_master/ofa/imagenet_classification/elastic_nn/modules/dynamic_layers.py", line 721, in get_active_subnet
E               sub_layer.conv1.conv.weight.data.copy_(
E           RuntimeError: The size of tensor a (1008) must match the size of tensor b (88) at non-singleton dimension 0
```

You can find more details about the execution [here](https://app.circleci.com/pipelines/github/pytorch/hub/2023/workflows/1fb1a4ce-17d5-45a7-b68a-1f92441072d0/jobs/2468)

Would you mind submitting a fix either in your own repo if relevant, or directly to the [once-for-all torchhub file](https://github.com/pytorch/hub/blob/master/pytorch_vision_once_for_all.md)? Thank you!

**Comment by han-cai** [comment]
Hi NicolasHug,

Thank you for informing us of the issue. I have submitted a pull request to fix it: 
https://github.com/pytorch/hub/pull/316

Best

**Comment by NicolasHug** [comment]
Thank you @han-cai !
