### ISSUE TITLE
Can't download `ofa_resnet50` super network

### ISSUE THREAD

**Issue by macsz** [mit-han-lab/once-for-all#83]
When attempting to download OFA ResNet50 network the following error is being thrown:

```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1xy6VIPEHXqbbqNu3xEZUxhp5FbTVs5cQ
```

**Comment by han-cai** [comment]
Hi,

I have updated the URL link. It should work now.

Best,
Han

**Comment by gegeo0** [comment]
[like]  Georgios Georgiadis reacted to your message:
________________________________

**Comment by hasanberatsoke-cy** [comment]
i take same error guys. what should i do?

`Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1xy6VIPEHXqbbqNu3xEZUxhp5FbTVs5cQ 
`

thank a lot
